### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rukachan** [Rukachan/Nature#12]
- [x] Add the ability to disable the worldgen of tainted soil
- [ ] Add Chisel support (like ancient trees)
- [ ] Add the ability to find saplings in chests (like ancient trees)
- [ ] Add the ability to get the trees via breeding (if Forestry is installed)
